settings:
  login_after_ticks: 20 # How many ticks after logging into the game should afk be checked? This is required for teleportation events when entering the game. (20 ticks = 1 second)
  how_many_blocks_move_needed: 1.0 # After how many blocks can the player move and write to the chat?

lang:
  chat_protect_message:
    - '&4AACS &7» &7To be able to talk in the chat, you need to advance &f%block% &7blocks.'
  permission_error_message:
    - '&4AACS &7» &7You don`t have permission for that.'
  aacs_command_usage:
    - '&6USAGE &7» &f/aacs reload › &7To reload the configuration.'
  aacs_reloaded_message:
    - '&4AACS &7» &aConfiguration reloaded.'